#!/bin/bash

{% if debian_scripts.postinst is defined %}
{% for script in debian_scripts.postinst %}
{{ script }}
{% endfor %}
{% endif %}


{% if settings.use_nginx|default %}
if pgrep nginx > /dev/null; then
    /etc/init.d/nginx reload 
fi
{% endif %}

{% if is_python|default %}
python -m compileall -q {{ pyfiles_path}} || true
{% endif %}
